# Generated by Django 4.0.4 on 2022-05-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Team_Members',
            new_name='Team_Member',
        ),
    ]
