# Generated by Django 4.0.4 on 2022-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Information', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
