# Generated by Django 4.0.4 on 2022-05-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services_Information', '0005_rename_images_service_image_service_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='list_item1',
            new_name='list_item',
        ),
        migrations.RemoveField(
            model_name='project',
            name='list_item2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='list_item3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='list_item4',
        ),
    ]
