# Generated by Django 4.0.4 on 2022-05-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='Banner',
        ),
    ]
