# Generated by Django 4.0.4 on 2022-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0002_rename_banners_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_info',
            old_name='site_link',
            new_name='site_email',
        ),
        migrations.AddField(
            model_name='site_info',
            name='site_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site_info',
            name='location',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site_info',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
