# Generated by Django 4.0.4 on 2022-05-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0003_rename_site_link_site_info_site_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
