# Generated by Django 4.0.4 on 2022-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0004_alter_testimony_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
