# Generated by Django 4.0.4 on 2022-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0005_rename_image_about_image1_about_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choose',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='choose',
            name='image2',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
