# Generated by Django 4.0.4 on 2022-05-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0006_rename_image_choose_image1_choose_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choose',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='choose',
            name='image2',
        ),
    ]
