# Generated by Django 4.0.4 on 2022-06-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Information', '0009_alter_site_info_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_info',
            name='section_contact_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
